name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROCESSING_TAG: processing-1293-4.3

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Processing
        uses: pr1metine/setup-processing@v2.1.0
        with:
          tag: ${{ env.PROCESSING_TAG }}
      - name: Export
        run: |
          cd ..
          processing-java --sketch="${{ github.event.repository.name }}" --output=out --force --export
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ github.event.repository.name }} (${{ matrix.os }})"
          path: |
            ./out/
            !./out/source/
