name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROCESSING_TAG: processing-1293-4.3

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    env:
      VARIANT: linux-amd64
    steps:
      - uses: actions/checkout@v4
      - name: Setup Processing
        uses: pr1metine/setup-processing@v2.1.0
        with:
          tag: "$PROCESSING_TAG"
      - name: Export
        run: processing-java --variant=$VARIANT --sketch="../${{ github.event.repository.name }}" --output=out --force --export
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "DWM_WARLOCK ($VARIANT)"
          path: |
            ./out/
            !./out/source/
  build-windows:
    runs-on: windows-2022
    env:
      VARIANT: windows-amd64
    steps:
      - uses: actions/checkout@v4
      - name: Setup Processing
        uses: pr1metine/setup-processing@v2.1.0
        with:
          tag: "$PROCESSING_TAG"
      - name: Export
        run: processing-java --variant=$VARIANT --sketch="../${{ github.event.repository.name }}" --output=out --force --export
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "DWM_WARLOCK ($VARIANT)"
          path: |
            ./out/
            !./out/source/
